### PR TITLE
Dashboard sort optimization + Use actual production map for subtotal and tooltip display

### PR DESCRIPTION
**Pull request by lovalmidas**
Sort is currently conducted with a database fetch, which takes a few seconds. This should not be necessary.

This PR changes it to use the existing cities list that is already retrieved and stored.

### CODE REVIEW

**Comment by lovalmidas** [comment]
An additional commit is added, to allow the tooltip and production subtotal use the production map, accounting for seasonal and region modifiers.
image

It might be more user-friendly for the tooltip to explicitly state what effect is applied rather than the result (users generally don't expect the tooltip numbers to change). Probably up for discussion.

**Comment by lovalmidas** [comment]
Another additional commit is added, the tooltip now separates the modifier value (additive) from the base value. This is the simplest case and does not separate the source of the modification (region, climate or season). Those probably belong outside the tooltip.
 
This commit also simplifies various subtotal elements into a common element template. We can now easily create new resources without requiring massive changes to the UI. Currently, the exceptions are pollution (due to the possible use of a function), workers (custom x/y display), tax income and money expenses (just so that money changes are listed last alongside tax details).

image

**Comment by warronbebster** [comment]
Can you modify this PR to not include the repo migration changes? There's already a PR for that and best practice is each PR should be a self-contained set of changes. That way I can accept this one without having to also accept the migration changes at the same time :)

**Comment by lovalmidas** [comment]
No problem. I had them on as they were needed to run mix setup, but I realized I can remove the files after and not include it in the commit history. I will exclude the files in the future.

**Review by warronbebster — APPROVED** [review]
Can you remove the migrations changes from this PR and open up a separate

**Pull request merged**
